#' Mask, Remove Outliers from, and Rescale a Raster
#'
#' Combined function for pre-processing tasks. If only the first argument is supplied, `mask.clean` is identical to `remove.outliers`. However, additional parameters allow the user to also mask the input raster with a QA layer (which can be generated if an HLS Fmask layer is supplied), as well as rescale it if it is not properly scaled.
#'
#' @param raster A SpatRaster, RasterLayer, or file path.
#' @param layer Layer for masking. Either a QA generated by `make.qa`, or an Fmask layer, in which case a QA layer will be generated and used for masking, but won't be included in the output.
#' @param layer.type Tells the function whether `layer` is a QA or Fmask layer. Valid options are "QA" or "FM."
#' @param scalar Target scale. If the average value of the raster differs from this number too greatly, the raster will be multiplied by this number.
#' @param tolerance Tolerated difference in significant figures between scalar and average raster value. Exceeding this value results in rescaling.
#' @param filename Output file path.
#' @param ... Additional argument to pass to `writeRaster` and `check.scale`.
#'
#' @return A SpatRaster.
#' @export
#'
#' @examples
#' #Load/create data
#' set.seed(1)
#' data(qa_ex)
#' r <- rast(matrix(rnorm(100), nrow = 10))
#'
#' #Compare before and after `mask.clean`
#' mean(values(r))
#' plot(r, main = "Raster")
#' plot(qa_ex, main = "QA layer")
#' r <- mask.clean(r, qa_ex, "QA", 10000)
#' mean(values(r), na.rm = TRUE)
#' plot(r, main = "Masked & Cleaned Raster")
mask.clean <- function(raster, layer = NULL, layer.type = NULL, scalar = NULL, tolerance = 1, filename = "", ...) {
  if(is.character(raster) | inherits(raster, "RasterLayer")){
    raster <- rast(raster)
  }
  if (!is.null(layer) | !is.null(layer.type)){
    if(is.character(layer) | inherits(layer, "RasterLayer")){
      layer <- rast(layer)
    }
    if(!is.null(layer) & !is.null(layer.type)){
      if(layer.type == "FM"){
        qa <- make.qa(layer, ...)
        raster <- mask(raster, qa)
      }
      else if(layer.type == "QA"){
        raster <- mask(raster, layer, ...)
      }
      else {
        stop("Invalid layer type. Choose 'FM' or 'QA.'")
      }
    }
    else{
      stop("`layer` or `layer.type` is `NULL`.")
    }
  }
  raster <- remove.outliers(raster)
  if(!is.null(scalar)){
    raster <- check.scale(raster, scalar, tolerance, ...)
  }
  if(filename != ""){
    writeRaster(raster, filename, ...)
  }
  return(raster)
}
